-- Phase 5 — daily morning briefings generated by Claude.

create table public.daily_briefings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  briefing_date date not null,
  headline text not null,
  body text not null,
  recovery_call text,
  nutrition_call text,
  schedule_call text,
  watch_for text,
  model text not null,
  raw jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, briefing_date)
);

create index daily_briefings_user_date_idx
  on public.daily_briefings (user_id, briefing_date desc);

alter table public.daily_briefings enable row level security;

create policy "Users can view their own briefings"
  on public.daily_briefings for select using (auth.uid() = user_id);
create policy "Users can insert their own briefings"
  on public.daily_briefings for insert with check (auth.uid() = user_id);
create policy "Users can update their own briefings"
  on public.daily_briefings for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own briefings"
  on public.daily_briefings for delete using (auth.uid() = user_id);
